### ISSUE TITLE
Automated testing in a Rails app with the Cronofy Client

### ISSUE THREAD

**Issue by connorshea** [cronofy/cronofy-ruby#84]
I see there's a `client_spec.rb` that includes some fake data: https://github.com/cronofy/cronofy-ruby/blob/5410bef43afa2c48f5e27f3eb0f3960a30e766b1/spec/lib/cronofy/client_spec.rb

Does anyone have a good system for mocking the data returned from various `Cronofy::Client` methods? Or would anyone be interested in providing it in the gem itself? I'd prefer to avoid VCR/WebMock stubbed requests if possible (I'd like to stub the methods themselves, e.g. `list_calendars`), but I acknowledge that may not be feasible here.

Thanks!

**Comment by AdamWhittingham** [comment]
Hi,

We don't prescribe any particular way of testing the API methods because of how varied the frameworks, preferences and use cases are. Test data is going to be most helpful when it relates to the context of what you're building, so it's a tricky thing for us to solve centrally.

There are example responses on our [API docs site](https://docs.cronofy.com/developers/api/) for each endpoint which are a great starting point, but you are best off making some queries against a dev app and choosing what you want to stub/mock/record so that your tests are as descriptive of your use case as possible.

Hope this helps!
